[package]
name = "fspy_nostd_alloc"
edition = "2024"
license.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
allocator-api2 = { workspace = true, features = ["alloc"] }
fspy_nostd = { workspace = true }

[target.'cfg(unix)'.dependencies]
bump-scope = { workspace = true }

[lints]
workspace = true
