use winapi::DEFINE_GUID;
use wincode::{SchemaRead, SchemaWrite};

use crate::ipc::{AccessMode, channel::ChannelConf};

// Generated by guidgen.exe
// {FC4845F1-3A8B-4F05-A3D3-A5E9E102AF33}
DEFINE_GUID!(
    PAYLOAD_ID,
    0xfc48_45f1,
    0x3a8b,
    0x4f05,
    0xa3,
    0xd3,
    0xa5,
    0xe9,
    0xe1,
    0x02,
    0xaf,
    0x33
);

#[derive(SchemaWrite, SchemaRead, Debug, Clone)]
pub struct Payload<'a> {
    pub channel_conf: ChannelConf,
    pub ansi_dll_path_with_nul: &'a [u8],
    /// Name of the named pipe the traced process connects to for blocking
    /// open/close callbacks. Empty when no callback is registered.
    pub callback_pipe_name: &'a [u8],
    /// Access-mode mask for the callback; meaningful only when
    /// `callback_pipe_name` is non-empty.
    pub callback_mask: AccessMode,
}
