[default.extend-words]
ratatui = "ratatui"
PUNICODE = "PUNICODE"
buid = "buid"

[files]
extend-exclude = [
  "crates/fspy_detours_sys/detours",
  "crates/fspy_detours_sys/src/generated_bindings.rs",
]
