[package]
name = "fspy_benchmark_launcher"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "fspy_benchmark_launcher"
test = false
doctest = false

[dependencies]
fspy = { workspace = true }
tokio = { workspace = true, features = ["macros", "process", "rt-multi-thread"] }
tokio-util = { workspace = true }
