[package]
name = "vt_shell"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
rust-version.workspace = true

[dependencies]
brush-parser = { workspace = true }
serde = { workspace = true, features = ["derive"] }
shell-escape = { workspace = true }
vt_casefold = { workspace = true, features = ["serde"] }
vt_str = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false
