[package]
name = "fspy_shared"
version = "0.0.0"
edition = "2024"
license.workspace = true
publish = false

[dependencies]
wincode = { workspace = true, features = ["derive"] }
allocator-api2 = { workspace = true, features = ["alloc"] }
bitflags = { workspace = true }
bumpalo = { workspace = true }
bstr = { workspace = true, features = ["alloc", "std"] }
bytemuck = { workspace = true, features = ["must_cast", "derive"] }
fspy_nostd = { workspace = true }
fspy_nostd_alloc = { workspace = true }
fspy_shm = { workspace = true }
fspy_ipc_str = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
vt_path = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
bytemuck = { workspace = true }
omnipath = { workspace = true }
winapi = { workspace = true, features = ["std"] }

[dev-dependencies]
assert2 = { workspace = true }
ctor = { workspace = true }
rustc-hash = { workspace = true }
subprocess_test = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "time"] }

[lints]
workspace = true

[lib]
doctest = false

[package.metadata.cargo-shear]
ignored = ["ctor"]
