[package]
name = "fspy_preload_unix"
edition = "2024"
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[target.'cfg(unix)'.dependencies]
anyhow = { workspace = true }
wincode = { workspace = true }
bstr = { workspace = true, default-features = false }
ctor = { workspace = true }
fspy_shared = { workspace = true }
fspy_shared_unix = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["signal", "fs", "socket", "mman", "time"] }

[target.'cfg(all(target_os = "linux", not(target_env = "musl"), any(target_arch = "aarch64", target_arch = "x86_64")))'.dependencies]
fspy_syscall_intercept = { workspace = true }

[lints]
workspace = true
