[package]
name = "fspy_preload_unix"
edition = "2024"
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[target.'cfg(unix)'.dependencies]
ctor = { workspace = true }
fspy_client_unix = { workspace = true }
fspy_shared = { workspace = true }
fspy_shared_unix = { workspace = true }
libc = { workspace = true }
nix = { workspace = true, features = ["signal", "fs", "socket", "mman", "time"] }
fspy_nostd = { workspace = true }
fspy_nostd_alloc = { workspace = true }

[lints]
workspace = true
